In [33]:
import tensorflow as tf
print(("Your version of TensorFlow: {0}").format(tf.__version__))

Your version of TensorFlow: 2.19.0


In [34]:
A = tf.constant([[4,3],
                [7,6]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [7, 6]], dtype=int32)>

In [35]:
V = tf.Variable([[3,4],
                 [5,6]])
B = tf.constant([[1,2],
                 [3,4]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
# Concatenate columns 
AB_Concate = tf.concat(values=[V,B], axis=0)
AB_Concate

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [37]:
# Concatenate columns 
AB_Concate = tf.concat(values=[V,B], axis=1)
AB_Concate

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 4, 1, 2],
       [5, 6, 3, 4]], dtype=int32)>

In [38]:
tensor = tf.zeros(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [39]:
tensor = tf.ones(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [40]:
reshape_tensor = tf.reshape(tensor= tensor,shape= [4,3])
reshape_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [41]:
tensor_1 = tf.random.uniform(shape=[3,4],dtype=tf.float32)
tensor_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.833532  , 0.9752897 , 0.7850814 , 0.43989432],
       [0.63313735, 0.8454708 , 0.80938685, 0.172387  ],
       [0.32072043, 0.5998734 , 0.8061161 , 0.71936   ]], dtype=float32)>

In [42]:
reshape_tensor_1 = tf.reshape(tensor= tensor_1, shape=[4,3])
reshape_tensor_1

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.833532  , 0.9752897 , 0.7850814 ],
       [0.43989432, 0.63313735, 0.8454708 ],
       [0.80938685, 0.172387  , 0.32072043],
       [0.5998734 , 0.8061161 , 0.71936   ]], dtype=float32)>

In [43]:
# typecast a tensor 
tensor_2 = tf.constant([[3.4,5.6],
                        [4.5,6.3],
                        [1.2,4.7],
                        [8.6,5.8]],
                        dtype=tf.float32)
tensor_2_as_int = tf.cast(tensor_2, tf.int16)
print(tensor_2)
print(tensor_2_as_int)

tf.Tensor(
[[3.4 5.6]
 [4.5 6.3]
 [1.2 4.7]
 [8.6 5.8]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[3 5]
 [4 6]
 [1 4]
 [8 5]], shape=(4, 2), dtype=int16)


In [44]:
a = tf.transpose(tensor_2_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int16, numpy=
array([[3, 4, 1, 8],
       [5, 6, 4, 5]], dtype=int16)>

In [45]:
# Mathsmetical operation 
A = tf.constant([[1,2],
                 [3,4]])
B = tf.constant([[5],
                 [6]])
AV = tf.matmul(A, B)
AV


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[17],
       [39]], dtype=int32)>

In [46]:
# Elements-wise multiplity
A = tf.multiply(A, B)
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [18, 24]], dtype=int32)>

In [47]:
# creating an indentify matrix
A = tf.constant([[3,9],
                 [2,4],
                 [5,19]])
rows, columns = A.shape
print('rows',rows, 'columns',columns)

# Making identity matrix 
A_identity = tf.eye(num_rows=rows,
                    num_columns=columns,
                    dtype= tf.int32)
A_identity

rows 3 columns 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]], dtype=int32)>